# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
  
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Add BepInEx nuget source
      run: dotnet nuget add source https://nuget.bepinex.dev/v3/index.json -n nuget.bepinex.dev
    - name: Add BepInEx packages
      run: | # adds https://nuget.bepinex.dev/packages/BepInEx.IL2CPP and https://nuget.bepinex.dev/packages/BepInEx.PluginInfoProps
        dotnet add package BepInEx.IL2CPP --version 6.0.0-pre.1
        dotnet add package BepInEx.PluginInfoProps --version 2.1.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal